### ISSUE TITLE
Chronoswitch shows up as a corrupted file, and won't launch

### ISSUE THREAD

**Issue by MustardBeef** [DaveeFTW/Chronoswitch#7]
I'm running 6.61 Infinity LME-2.3, on a Blue JP 3000
I'm using Chronoswitch 7.2, but it shows up as "corrupted file," and won't start.

I don't know the history of this system, but I want to play my US purchased games on here, which will launch, but then close out, and I think that is because I am running CFW, but I am uncertain, and figured that undoing CFW would be a good first step.

Thanks for the help!

**Comment by TheZett** [comment]
Make sure Chronoswitch is located in the correct folder. The path should look like this:

X:/PSP/GAME/DOWNGRADE/EBOOT.PBP

The easiest way to do this is by simply copying the "PSP" folder from the archive to the root directory of your PSP's memory stick.
If done correctly, it should show up on the PSP as a blue icon with the number 6.20 on it.

**Comment by MustardBeef** [comment]
Thank you, the path listed was X:/PSP/GAME/UPGRADE/EBOOT.PBP!

**Comment by MustardBeef** [comment]
Now it is giving me an error 80010002, but I can open Cronoswitch now. Running on an o3g

**Comment by TheZett** [comment]
Reread the readme file in its entirety please.

You need the Chronoswitch Downgrader and a PSP Updater file that you want to downgrade to (e.g. 6.61 OFW).
The PSP Updater file has to be placed in the following path:

X:/PSP/GAME/UPDATE/EBOOT.PBP
